# https://wiki.hypr.land/Configuring/Window-Rules/

# fullscreen in only window in workspace
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = match:workspace w[tv1], border_size 0
windowrule = match:workspace w[tv1], rounding 0
windowrule = match:workspace f[1], border_size 0
windowrule = match:workspace f[1], rounding 0

# Picture-in-Picture
windowrule = match:title ^Picture-in-Picture$, float true
windowrule = match:title ^Picture-in-Picture$, pin true
windowrule = match:title ^Picture-in-Picture$, no_anim on
windowrule = match:title ^Picture-in-Picture$, size 266 150
windowrule = match:title ^(Picture-in-Picture)$, center 90 90

# Ignore maximize requests from apps
# windowrule = suppressevent maximize, class:.*
#
# # Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
