# # https://wiki.hypr.land/Configuring/Window-Rules/
# 
# # fullscreen in only window in workspace
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]
# 
# # Picture-in-Picture
# windowrulev2 = float, title:^Picture-in-Picture$
# windowrulev2 = pin, title:^Picture-in-Picture$
# windowrulev2 = noanim, title:^Picture-in-Picture$
# windowrulev2 = size 266 150, title:^Picture-in-Picture$
# windowrulev2 = center 90 90, title:^(Picture-in-Picture)$
# 
# # Fix Flameshot
# windowrulev2=move 0 0,class:(flameshot),title:(flameshot)
# windowrulev2=pin,class:(flameshot),title:(flameshot)
# windowrulev2=fullscreenstate,class:(flameshot),title:(flameshot)
# windowrulev2=float,class:(flameshot),title:(flameshot)
# 
# # Ignore maximize requests from apps
# windowrule = suppressevent maximize, class:.*
# 
# # Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
